"""Adicionando dados de notificacao aos clientes

Revision ID: 6991f5ee2b7c
Revises: 28cab9b109b5
Create Date: 2026-08-02 14:33:17.203727

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6991f5ee2b7c'
down_revision = '28cab9b109b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('observacoes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('recebe_notificacao', sa.Boolean(), nullable=False))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
        batch_op.drop_column('recebe_notificacao')
        batch_op.drop_column('observacoes')

    # ### end Alembic commands ###
