"""Adicionando dados do cliente e veiculo na ordem

Revision ID: 8804f13da7c8
Revises: b8528c538915
Create Date: 2026-08-03 19:33:48.848000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8804f13da7c8'
down_revision = 'b8528c538915'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordens_servico', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cliente_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('placa', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('marca', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('modelo', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('ano', sa.Integer(), nullable=True))
        batch_op.alter_column('veiculo_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_ordens_servico_cliente_id'), ['cliente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ordens_servico_placa'), ['placa'], unique=False)
        batch_op.create_foreign_key(None, 'clientes', ['cliente_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordens_servico', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_ordens_servico_placa'))
        batch_op.drop_index(batch_op.f('ix_ordens_servico_cliente_id'))
        batch_op.alter_column('veiculo_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('ano')
        batch_op.drop_column('modelo')
        batch_op.drop_column('marca')
        batch_op.drop_column('placa')
        batch_op.drop_column('cliente_id')

    # ### end Alembic commands ###
