"""Criando tabela veiculos

Revision ID: 373c221d9c5c
Revises: 6991f5ee2b7c
Create Date: 2026-08-02 15:09:49.064032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '373c221d9c5c'
down_revision = '6991f5ee2b7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('veiculos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('placa', sa.String(length=10), nullable=False),
    sa.Column('marca', sa.String(length=50), nullable=False),
    sa.Column('modelo', sa.String(length=80), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=True),
    sa.Column('quilometragem_atual', sa.Integer(), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('veiculos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_veiculos_cliente_id'), ['cliente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_veiculos_placa'), ['placa'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('veiculos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_veiculos_placa'))
        batch_op.drop_index(batch_op.f('ix_veiculos_cliente_id'))

    op.drop_table('veiculos')
    # ### end Alembic commands ###
