"""Criando tabela ordens_servico

Revision ID: b8528c538915
Revises: 373c221d9c5c
Create Date: 2026-08-02 15:37:05.073476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8528c538915'
down_revision = '373c221d9c5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ordens_servico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('veiculo_id', sa.Integer(), nullable=False),
    sa.Column('data_servico', sa.Date(), nullable=False),
    sa.Column('quilometragem', sa.Integer(), nullable=False),
    sa.Column('descricao_servico', sa.String(length=150), nullable=False),
    sa.Column('tipo_oleo', sa.String(length=100), nullable=True),
    sa.Column('quantidade_litros', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('filtro_oleo', sa.Boolean(), nullable=False),
    sa.Column('filtro_ar', sa.Boolean(), nullable=False),
    sa.Column('filtro_combustivel', sa.Boolean(), nullable=False),
    sa.Column('proxima_troca_km', sa.Integer(), nullable=True),
    sa.Column('proxima_troca_data', sa.Date(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['veiculo_id'], ['veiculos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ordens_servico', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ordens_servico_veiculo_id'), ['veiculo_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordens_servico', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ordens_servico_veiculo_id'))

    op.drop_table('ordens_servico')
    # ### end Alembic commands ###
