from .dashboard_web_routes import dashboard_web_bp
from .cliente_web_routes import cliente_web_bp
from .ordem_servico_web_routes import ordem_servico_web_bp
from .notificacao_web_routes import notificacao_web_bp